### ISSUE TITLE
"wrong signature!" "amount" when trying to donate to wikimedia (coinbase)

### ISSUE THREAD

**Issue by bolapara** [hivewallet/hive-android#13]
![screenshot from 2014-07-30 11 10 35](https://cloud.githubusercontent.com/assets/141778/3753851/f136a254-1815-11e4-9283-6a8dfac44859.png)

![screenshot_2014-07-30-11-13-32](https://cloud.githubusercontent.com/assets/141778/3753924/79283240-1816-11e4-8198-9357a69f1e0e.png)

**Comment by javgh** [comment]
Thanks for the report!

I went to the donation screen myself and for me it scanned fine. Maybe it was a temporary hiccup on Coinbase's part? I'll leave the ticket open for a while and see if any other reports are coming in.

**Comment by schildbach** [comment]
I saw this with Coinbase from time to time too. They seem to be using floats for Bitcoin values at some point. This results in a tiny difference of the BIP21 amount and the BIP70 amount. Maybe download the PR and decode it to see yourself. The BIP21 amount is 0.01741 BTC.

**Comment by javgh** [comment]
Indeed, that seems to be the problem! I ran `protoc --decode_raw` on the Coinbase request and the amount field has the value 1740999 .

@schildbach: This check, that the BIP21 amount matches the BIP70 amount, is an additional security check by Bitcoin Wallet which is not necessarily required by the standard, right? So other clients will probably not run into this, yes? .. I mean, it's still a Coinbase bug, but just to confirm my understanding of this.

**Comment by schildbach** [comment]
Afaik there are no other clients implementing BIP70 except bitcoin-qt.

I reported this bug to Coinbase about 2 months ago and the guy said he fixed it…

**Comment by javgh** [comment]
Hive OS X also implements BIP70 and GreenAddress.it has support as well. There might be others, but true, it's still only a few.

I also now reported the bug to Coinbase. Hopefully they'll fix it for good this time - we'll see. I'm closing this for now.

**Comment by verhovsky** [comment]
Just got this bug trying to buy reddit gold.
