### ISSUE TITLE
Scanning QR code of a transaction and broadcast it

### ISSUE THREAD

**Issue by weilu** [hivewallet/hive-android#14]
This is a requested feature that can be used to facilitate transaction built on an offline computer. If we decide to support this feature, we'll need to find a place for it on the UI.

Related: https://github.com/hivewallet/hive-ios/issues/25

**Comment by javgh** [comment]
That's actually already possible with Hive Android. If you scan such a QR code with the standard camera action, it will automatically recognize that it's a transaction and will import it, if it's valid.

It's not specifically hinted at in the UI though, that the camera action can be used in this way. But maybe that's fine. Seems like a power user feature - they can read the FAQ. ;-)

**Comment by weilu** [comment]
sweet! I didn't know that :)
