### ISSUE TITLE
Encrypted backups

### ISSUE THREAD

**Issue by bolapara** [hivewallet/hive-android#7]
Encrypted backups would be much safer.  Show a generated passphrase on the screen that decrypts the private key that is saved to storage/cloud services.

**Comment by javgh** [comment]
Hive Android supports encrypted backups. In fact, it asks for an encryption password right after you select the backup option. Did you mean to file this issue for another project? Please re-open if I misunderstood your request.

**Comment by bolapara** [comment]
Yep, I was confused, my apologies.  Filing correct request for hive shortly.
